---
- name: Drs Infra
  hosts: all
  vars_files:
    - vault.yml
  
  tasks:
    - name: Deploy psql
      vars:
        ct_name: psql
      include_role:
        name: psql

    - name: Deploy UptimeKuma
      vars:
        ct_name: kuma
      include_role:
        name: kuma

    - name: Deploy glance
      vars:
        ct_name: glance
      include_role:
        name: glance

    - name: Deploy Trilium
      vars:
        ct_name: trilium
      include_role:
        name: trilium

    - name: Deploy Calibre
      vars:
        ct_name: calibre
      include_role:
        name: calibre

    - name: Deploy Jellyfin
      vars:
        ct_name: jellyfin
      include_role:
        name: jellyfin

    - name: Deploy MiniDLNA
      vars:
        ct_name: minidlna
      include_role:
        name: minidlna

    - name: Deploy miniflux
      vars:
        ct_name: miniflux
      include_role:
        name: miniflux

    - name: Deploy homebox
      vars:
        ct_name: homebox
      include_role:
        name: homebox