--- 

pve_ct_template_id: 111
ct_name: psql
pg_db_net: 10.11.12.0/24
pg_version: 17
pg_dir: "/var/lib/postgresql"
pg_conf_dir: "/etc/postgresql"
pg_hba_conf: "{{pg_conf_dir}}/pg_hba.conf"
pg_conf_file: "{{pg_conf_dir}}/postgresql.conf"